BINARY = main
OBJS += usb.o light.o colorsys.o printf.o

DEFS += -DPRINTF_DISABLE_SUPPORT_FLOAT -DPRINTF_DISABLE_SUPPORT_EXPONENTIAL -DPRINTF_DISABLE_SUPPORT_LONG_LONG -DPRINTF_DISABLE_SUPPORT_PTRDIFF_T

LDSCRIPT = stm32f103x4.ld

include Makefile.include
